In [14]:
import pandas as pd
import numpy as np
import csv
import gensim
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from nltk.stem.wordnet import WordNetLemmatizer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from nltk.stem.porter import PorterStemmer
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.pipeline import Pipeline
from nltk.corpus import stopwords
from string import punctuation
import seaborn as sns
import pandas as pd
import numpy as np
import nltk
import re
import nltk
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
import matplotlib.pyplot as plt
from scipy import sparse

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/emmeline.tsen/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/emmeline.tsen/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [117]:
import pandas as pd

df = pd.read_csv('reviews.csv')
df.dropna(subset=['comments'])
# df = df[pd.notnull(df['comments'])]
df = df[['listing_id', 'id', 'comments']]
df.head()

   listing_id     id                                           comments
0         958   5977  Our experience was, without a doubt, a five st...
1         958   6660  Returning to San Francisco is a rejuvenating t...
2         958  11519  We were very pleased with the accommodations a...
3         958  16282  We highly recommend this accomodation and agre...
4         958  26008  Holly's place was great. It was exactly what I...

In [121]:
df

,listing_id,id,comments
0,958,5977,"Our experience was, without a doubt, a five st..."
1,958,6660,Returning to San Francisco is a rejuvenating t...
2,958,11519,We were very pleased with the accommodations a...
3,958,16282,We highly recommend this accomodation and agre...
4,958,26008,Holly's place was great. It was exactly what I...
5,958,29240,"On top of all that has been said previously, I..."
6,958,32988,This apartment was everything I could have hop...
7,958,220443,Great place to stay. I would highly recommend...
8,958,567690,"Great location in San Francisco, really felt l..."
9,958,1786860,We had a wonderful time at Holly & Davids plac...
10,958,2214082,Holly's unit is comfortable and convenient if ...
11,958,2263537,Holly's place was great. I would definitely s...
12,958,3553733,This is a great place in a wonderful neighbor ...
13,958,4392049,Our stay at Holly's apartment was absolutely w...
14,958,5040421,Great location near Haight Street and close to...
15,958,5171535,Truly amazing place - great location near Haig...
16,958,5267286,"We really enjoyed staying in this cute, and ai..."
17,958,5905160,This was the perfect little rental suite. It w...
18,958,5996571,Great position for exploring San Francisco- cl...
19,958,7364408,We had the greatest stay at Holly & David's ga...
20,958,7817720,What a gem! Holly (and her adorable son!) gree...
21,958,9049799,We couldn't have asked for a better place to s...
22,958,12766593,Holly's garden unit is very nice. It is clean...
23,958,12984959,Holly's lovely apartment is exactly as adverti...
24,958,14349227,We visited San Fran for a mix of work and leis...
25,958,14492437,Great place! Wonderful neighborhood! Together...
26,958,16609563,"Note: My mother, father, and younger brother s..."
27,958,16843898,"Holly's garden apartment was fantastic, there'..."
28,958,19415506,Holly was great and always accessible. The gar...
29,958,19869583,This was my first experience with Airbnb and i...
...,...,...,...
366613,38804506,538102004,"房间非常干净,就在湾区,附近有很多好吃的,总之强烈推荐!"
366614,38804506,541728256,Nice apartment. Very clean and easy to access....
366615,38815628,535138330,"The place was much better then we expected, we..."
366616,38815628,536021587,Vladimir's place was awesome! Great and quiet ...
366617,38815628,539186679,"The apartment is incredible nice , comfortable..."
366618,38819934,535154372,Had a wonderful time with my husband and a bab...
366619,38819934,536435303,We loved staying at Igor‘s place in San Franci...
366620,38819934,538540541,"Great place. Clean, well lit, breakfast was a ..."
366621,38822604,546628316,Zhaochang’s place was perfect for our stay in ...
366622,38828345,541679270,Be aware
366623,38828345,543441913,We had a great stay at Adrienne's! The apartme...
366624,38850031,545172137,As a first-time host Melissa did everything ri...
366625,38915404,538545871,The location was just great. My partner and I ...
366626,38927584,541233653,The host canceled this reservation 27 days bef...
366627,38955191,542733480,The space is beautiful and was in great drivin...
366628,38961739,539609808,I couldn't recommend this place more! Just ste...
366629,38977592,538499064,A really comfortable spot close to great resta...
366630,38977592,540528443,Awesome
366631,38979741,538356719,An affordable place in the good area of San Fr...
366632,38979868,540064618,Had a great time staying! Very thought through...
366633,38979868,541130081,Awesome place! Great location and excellent va...
366634,38979868,543467004,I enjoyed staying at Igor's place. \nIt's loc...
366635,38984642,544691900,.
366636,38984642,545637912,Joyce had been a great host for my weekend tri...
366637,38985258,546586277,This place was a amazing. Sonya was great and...
366638,39059847,546662295,What a steal for the price!\nMy partner and I ...
366639,39137417,543048610,The host canceled this reservation 5 days befo...
366640,39157824,544269028,Communication was great and the place was real...
366641,39225180,546511107,Nice location and a great view of the ocean. ...
366642,39258642,544849536,The host canceled this reservation 7 days befo...

In [15]:
def cleaning(raw_news):
    import nltk
    
    # 1. Remove non-letters/Special Characters and Punctuations.
    news = re.sub("[^a-zA-Z]", " ", str(raw_news))
    
    # 2. Convert to lower case.
    news =  news.lower()
    
    # 3. Tokenize.
    news_words = nltk.word_tokenize( news)
    
    # 4. Convert the stopwords list to "set" data type.
    stops = set(nltk.corpus.stopwords.words("english"))
    
    # 5. Remove stop words. 
    words = [w for w in  news_words  if not w in stops]
    
    # 6. Lemmentize 
    wordnet_lem = [ WordNetLemmatizer().lemmatize(w) for w in words ]
    
    # 7. Stemming
    stems = [nltk.stem.SnowballStemmer('english').stem(w) for w in wordnet_lem ]
    
    # 8. Join the stemmed words back into one string separated by space, and return the result.
    return " ".join(stems)

In [122]:
def clean_df():
    df['clean_comments'] = df['comments'].apply(cleaning)

In [123]:
clean_df()
df

,listing_id,id,comments,clean_comments
0,958,5977,"Our experience was, without a doubt, a five st...",experi without doubt five star experi holli hu...
1,958,6660,Returning to San Francisco is a rejuvenating t...,return san francisco rejuven thrill time enhan...
2,958,11519,We were very pleased with the accommodations a...,pleas accommod friend neighborhood abl make se...
3,958,16282,We highly recommend this accomodation and agre...,high recommend accomod agre previous post holl...
4,958,26008,Holly's place was great. It was exactly what I...,holli place great exact need perfect locat sup...
5,958,29240,"On top of all that has been said previously, I...",top said previous would add quiet place holli ...
6,958,32988,This apartment was everything I could have hop...,apart everyth could hope place extrem well app...
7,958,220443,Great place to stay. I would highly recommend...,great place stay would high recommend superb l...
8,958,567690,"Great location in San Francisco, really felt l...",great locat san francisco realli felt like loc...
9,958,1786860,We had a wonderful time at Holly & Davids plac...,wonder time holli david place perfect famili k...
10,958,2214082,Holly's unit is comfortable and convenient if ...,holli unit comfort conveni wish stay haight ne...
11,958,2263537,Holly's place was great. I would definitely s...,holli place great would definit stay neighborh...
12,958,3553733,This is a great place in a wonderful neighbor ...,great place wonder neighbor central locat lowe...
13,958,4392049,Our stay at Holly's apartment was absolutely w...,stay holli apart absolut wonder neighborhood b...
14,958,5040421,Great location near Haight Street and close to...,great locat near haight street close muni get ...
15,958,5171535,Truly amazing place - great location near Haig...,truli amaz place great locat near haight stree...
16,958,5267286,"We really enjoyed staying in this cute, and ai...",realli enjoy stay cute airi garden apart littl...
17,958,5905160,This was the perfect little rental suite. It w...,perfect littl rental suit equip everyth need i...
18,958,5996571,Great position for exploring San Francisco- cl...,great posit explor san francisco close muni ap...
19,958,7364408,We had the greatest stay at Holly & David's ga...,greatest stay holli david garden unit ask bett...
20,958,7817720,What a gem! Holly (and her adorable son!) gree...,gem holli ador son greet u door warmth quick a...
21,958,9049799,We couldn't have asked for a better place to s...,ask better place stay hous locat quiet residen...
22,958,12766593,Holly's garden unit is very nice. It is clean...,holli garden unit nice clean comfort garden re...
23,958,12984959,Holly's lovely apartment is exactly as adverti...,holli love apart exact advertis first great ne...
24,958,14349227,We visited San Fran for a mix of work and leis...,visit san fran mix work leisur seattl terrif t...
25,958,14492437,Great place! Wonderful neighborhood! Together...,great place wonder neighborhood togeth make su...
26,958,16609563,"Note: My mother, father, and younger brother s...",note mother father younger brother stay holli ...
27,958,16843898,"Holly's garden apartment was fantastic, there'...",holli garden apart fantast way describ bed ext...
28,958,19415506,Holly was great and always accessible. The gar...,holli great alway access garden unit awesom pe...
29,958,19869583,This was my first experience with Airbnb and i...,first experi airbnb complet posit apart spacio...
...,...,...,...,...
366613,38804506,538102004,"房间非常干净,就在湾区,附近有很多好吃的,总之强烈推荐!",
366614,38804506,541728256,Nice apartment. Very clean and easy to access....,nice apart clean easi access close golden gate...
366615,38815628,535138330,"The place was much better then we expected, we...",place much better expect felt like home five s...
366616,38815628,536021587,Vladimir's place was awesome! Great and quiet ...,vladimir place awesom great quiet locat near p...
366617,38815628,539186679,"The apartment is incredible nice , comfortable...",apart incred nice comfort clean necessari bed ...
366618,38819934,535154372,Had a wonderful time with my husband and a bab...,wonder time husband babi hous clean new easi c...
366619,38819934,536435303,We loved staying at Igor‘s place in San Franci...,love stay igor place san francisco lucki first...
366620,38819934,538540541,"Great place. Clean, well lit, breakfast was a ...",great place clean well lit breakfast nice touc...
366621,38822604,546628316,Zhaochang’s place was perfect for our stay in ...,zhaochang place perfect stay san francisco hou...
366622,38828345,541679270,Be aware,awar
366623,38828345,543441913,We had a great stay at Adrienne's! The apartme...,great stay adrienn apart thought arrang welcom...
366624,38850031,545172137,As a first-time host Melissa did everything ri...,first time host melissa everyth right love hom...
366625,38915404,538545871,The location was just great. My partner and I ...,locat great partner love go tiki bar tradr sam...
366626,38927584,541233653,The host canceled this reservation 27 days bef...,host cancel reserv day arriv autom post
366627,38955191,542733480,The space is beautiful and was in great drivin...,space beauti great drive distanc anyth sf noel...
366628,38961739,539609808,I couldn't recommend this place more! Just ste...,recommend place step away reason came san fran...
366629,38977592,538499064,A really comfortable spot close to great resta...,realli comfort spot close great restaur califo...
366630,38977592,540528443,Awesome,awesom
366631,38979741,538356719,An affordable place in the good area of San Fr...,afford place good area san francisco flat quie...
366632,38979868,540064618,Had a great time staying! Very thought through...,great time stay thought stylish place amen lov...
366633,38979868,541130081,Awesome place! Great location and excellent va...,awesom place great locat excel valu high recom...
366634,38979868,543467004,I enjoyed staying at Igor's place. \nIt's loc...,enjoy stay igor place locat quiet clean area s...
366635,38984642,544691900,.,
366636,38984642,545637912,Joyce had been a great host for my weekend tri...,joyc great host weekend trip san francisco arr...
366637,38985258,546586277,This place was a amazing. Sonya was great and...,place amaz sonya great communic u frequent pro...
366638,39059847,546662295,What a steal for the price!\nMy partner and I ...,steal price partner realli enjoy stay hip mode...
366639,39137417,543048610,The host canceled this reservation 5 days befo...,host cancel reserv day arriv autom post
366640,39157824,544269028,Communication was great and the place was real...,communic great place realli easi find host rea...
366641,39225180,546511107,Nice location and a great view of the ocean. ...,nice locat great view ocean recommend cristina...
366642,39258642,544849536,The host canceled this reservation 7 days befo...,host cancel reserv day arriv autom post

In [125]:
# df.to_csv('cleaned_comments.csv')

In [126]:
df.iloc[-1]

listing_id                                                 39258642
id                                                        544849536
comments          The host canceled this reservation 7 days befo...
clean_comments              host cancel reserv day arriv autom post
Name: 366642, dtype: object

In [130]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyser = SentimentIntensityAnalyzer()

In [83]:
# Using the compound score for the sentiment analysis score
# It calculates the sum of all the lexicon ratings which have been normalized between 
# -1(most extreme negative) and +1 (most extreme positive)
def sentiment_analyzer_scores(sentence):
    score = analyser.polarity_scores(sentence)
#     print("{:-<40} {}".format(sentence, str(score)))
    return str(score['compound'])

In [128]:
sentiment_analyzer_scores(df.iloc[0].clean_comments)

0.9314

In [129]:
df['sentiment_score'] = ''

In [131]:
for i in range(len(df)):
    df.at[i,'sentiment_score'] = sentiment_analyzer_scores(df.iloc[i].clean_comments)

In [133]:
for i in range(len(df)):
    df.at[i,'senti_score_float'] = float(df.iloc[i].sentiment_score)

In [138]:
# df.to_csv('sentiment_scores.csv')

In [139]:
df.head()

,listing_id,id,comments,clean_comments,sentiment_score,senti_score_float
0,958,5977,"Our experience was, without a doubt, a five st...",experi without doubt five star experi holli hu...,0.9314,0.9314
1,958,6660,Returning to San Francisco is a rejuvenating t...,return san francisco rejuven thrill time enhan...,0.9451,0.9451
2,958,11519,We were very pleased with the accommodations a...,pleas accommod friend neighborhood abl make se...,0.8779,0.8779
3,958,16282,We highly recommend this accomodation and agre...,high recommend accomod agre previous post holl...,0.9741,0.9741
4,958,26008,Holly's place was great. It was exactly what I...,holli place great exact need perfect locat sup...,0.9538,0.9538

In [140]:
df.iloc[-2]

listing_id                                                    39225180
id                                                           546511107
comments             Nice location and a great view of the ocean.  ...
clean_comments       nice locat great view ocean recommend cristina...
sentiment_score                                                 0.9382
senti_score_float                                               0.9382
Name: 366641, dtype: object

In [142]:
# Taking the average of all sentiment scores for each listing id
mean_senti_score = df.groupby(['listing_id'], as_index=False)['senti_score_float'].mean()

In [143]:
mean_senti_score.head()

   listing_id  senti_score_float
0         958           0.769675
1        3850           0.796945
2        5858           0.821313
3        7918           0.715800
4        8142           0.763887

In [147]:
mean_senti_score.to_csv('mean_senti_score.csv')

In [145]:
mean_senti_score

      listing_id  senti_score_float
0            958           0.769675
1           3850           0.796945
2           5858           0.821313
3           7918           0.715800
4           8142           0.763887
5           8339           0.928354
6           8739           0.838653
7           9225           0.742182
8          10251           0.797342
9          10578           0.885328
10         10820           0.738735
11         10824           0.712980
12         10832           0.845442
13         12041           0.711633
14         12042           0.851260
15         12522           0.869727
16         12584           0.813624
17         14125           0.782289
18         17132           0.623114
19         18231           0.772605
20         18904           0.798108
21         21334           0.821571
22         21914           0.727657
23         23630           0.810842
24         24450           0.789955
25         24463           0.823915
26         24685           0.819385
27         24723           0.795049
28         25094           0.816444
29         25463           0.794495
...          ...                ...
6476    38675661           0.823350
6477    38702176           0.859100
6478    38702397           0.913900
6479    38703237           0.922750
6480    38730288           0.458800
6481    38735463           0.698750
6482    38757698           0.476700
6483    38794038           0.934733
6484    38795847           0.622800
6485    38801017           0.847600
6486    38804506           0.706280
6487    38815628           0.870167
6488    38819934           0.948867
6489    38822604           0.931300
6490    38828345           0.312450
6491    38850031           0.957800
6492    38915404           0.943200
6493    38927584          -0.250000
6494    38955191           0.848100
6495    38961739           0.872000
6496    38977592           0.382500
6497    38979741           0.868900
6498    38979868           0.914300
6499    38984642           0.479200
6500    38985258           0.624900
6501    39059847           0.950100
6502    39137417          -0.250000
6503    39157824           0.938200
6504    39225180           0.938200
6505    39258642          -0.250000

[6506 rows x 2 columns]

In [166]:
senti = mean_senti_score

In [174]:
senti.head()

   listing_id  senti_score_float
0         958           0.769675
1        3850           0.796945
2        5858           0.821313
3        7918           0.715800
4        8142           0.763887

In [176]:
senti = senti.rename(columns={"listing_id": "id", "senti_score_float": "senti_score"})

In [177]:
senti.head()

     id  senti_score
0   958     0.769675
1  3850     0.796945
2  5858     0.821313
3  7918     0.715800
4  8142     0.763887

In [178]:
#senti.to_csv('senti_score_v2.csv')